name: mlops-reproducible
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - pandas=2.0
  - numpy=1.24
  - scikit-learn=1.3
  - matplotlib=3.7
  - seaborn=0.12
  - pyyaml=6.0
  - joblib=1.3
  - pip:
    - mlflow==2.8.1
    - dvc==3.30.0
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - pytest==7.4.3
    - jupyter==1.0.0