data:
  raw: data/raw/ObesityDataSet_raw_and_data_sinthetic.csv
  interim: data/interim/obesity_clean.csv
  processed: data/processed/features.csv
  target: NObeyesdad

columns:
  categorical: [Gender, family_history_with_overweight, FAVC, CAEC, SMOKE, SCC, CALC, MTRANS]
  numerical:   [Age, Height, Weight, FCVC, NCP, CH2O, FAF, TUE]

validation:
  ranges:
    Age:    {min: 10,  max: 90}
    Height: {min: 1.2, max: 2.2}
    Weight: {min: 30,  max: 250}
    FCVC:   {min: 1,   max: 3}
    NCP:    {min: 1,   max: 6}
    CH2O:   {min: 1,   max: 3}
    FAF:    {min: 0,   max: 3}
    TUE:    {min: 0,   max: 2}
  outlier_action: clip   # clip | drop | flag

imputation:
  numeric_strategy: median     # median | mean | zero | none
  categorical_strategy: mode   # mode | constant | none
  categorical_fill_value: UNKNOWN

normalization:
  strip_strings: true
  lowercase: false
  collapse_spaces: true

features:
  categorical: [Gender, family_history_with_overweight, FAVC, CAEC, SMOKE, SCC, CALC, MTRANS]
  numerical:   [Age, Height, Weight, FCVC, NCP, CH2O, FAF, TUE]
  encoder: onehot        # onehot | ordinal | label
  scaler: standard       # standard | minmax | robust | none
  save_artifacts: true
  artifacts_dir: models/features

# Configuración del modelo
model:
  type: random_forest     # random_forest | logistic_regression
  n_estimators: 300
  max_depth: null
  class_weight: balanced

# Configuración del split
split:
  test_size: 0.2
  random_state: 52