name: MLOps Reproducible Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup DVC
      run: |
        dvc --version
        
    - name: Run tests
      run: |
        pytest tests/ -v
        
    - name: Run DVC pipeline
      run: |
        dvc repro --dry
        
    - name: Check data quality
      run: |
        python -c "import pandas as pd; print('Data validation passed')"